#include "../include/tables.h"

#include <stddef.h>
#include <string.h>

unsigned char character_map[256];

const char *months_xxx[12] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
const char *days_xxx[7] = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };

const char *fun_facts[1002] = {
    "The world's oldest wooden wheel has been around for more than 5,000 years.",
    "Dead skin cells are a main ingredient in household dust.",
    "Sudan has more pyramids than any country in the world.",
    "The bumblebee bat is the world's smallest mammal.",
    "More human twins are being born now than ever before.",
    "A narwhal's tusk reveals its past living conditions.",
    "The first person convicted of speeding was going eight mph.",
    "\"New car smell\" is the scent of dozens of chemicals.",
    "The world wastes about 1 billion metric tons of food each year.",
    "The smallest penguin on the planet is only 16 inches tall.",
    "The Eiffel Tower can grow more than six inches during the summer due to thermal expansion.",
    "The unicorn is the national animal of Scotland.",
    "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    "The human nose can remember 50,000 different scents.",
    "The loudest sound ever recorded was the eruption of Krakatoa in 1883, which could be heard 3,000 miles away.",
    "The longest time between two twins being born is 87 days.",
    "The total weight of all the ants on Earth is about the same as the weight of all the humans on Earth.",
    "The longest word that can be typed using only the left hand on a QWERTY keyboard is \"stewardesses\".",
    "The world's largest waterfall is underwater, between Greenland and Iceland.",
    "Honey never spoils due to its low water content; archaeologists have found edible honey in ancient Egyptian tombs.",
    "The circulatory system is more than 60,000 miles long.",
    "There are parts of Africa in all four hemispheres.",
    "The cornea is one of only two parts of the human body without blood vessels.",
    "A one-way trip on the Trans-Siberian Railway involves crossing 3,901 bridges.",
    "There's enough gold inside Earth to coat the planet.",
    "McDonald's once made bubblegum-flavored broccoli.",
    "Samsung tests phone durability with a butt-shaped robot.",
    "If you have 3 quarters, 4 dimes, and 4 pennies, you have $1.19. You also have the largest amount of money in coins without being able to make change for a dollar.",
    "The numbers '172' can be found on the back of the U.S. $5 dollar bill in the bushes at the base of the Lincoln Memorial.",
    "President Kennedy was the fastest random speaker in the world with upwards of 350 words per minute.",
    "In the average lifetime, a person will walk the equivalent of 5 times around the equator.",
    "Odontophobia is the fear of teeth.",
    "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.",
    "In the early days of the telephone, operators would pick up a call and use the phrase, \"Well, are you there?\". It wasn't until 1895 that someone suggested answering the phone with the phrase \"number please?\"",
    "The surface area of an average-sized brick is 79 cm squared.",
    "According to suicide statistics, Monday is the favored day for self-destruction.",
    "Cats sleep 16 to 18 hours per day.",
    "The most common name in the world is Mohammed.",
    "It is believed that Shakespeare was 46 around the time that the King James Version of the Bible was written. In Psalms 46, the 46th word from the first word is shake and the 46th word from the last word is spear.",
    "Karaoke means \"empty orchestra\" in Japanese.",
    "The Eisenhower interstate system requires that one mile in every five must be straight. These straight sections are usable as airstrips in times of war or other emergencies.",
    "The first known contraceptive was crocodile dung, used by Egyptians in 2000 B.C.",
    "Rhode Island is the smallest state with the longest name. The official name, used on all state documents, is \"Rhode Island and Providence Plantations.\"",
    "When you die your hair still grows for a couple of months.",
    "There are two credit cards for every person in the United States.",
    "The sound of E.T. walking was made by someone squishing her hands in jelly.",
    "1 in 5,000 north Atlantic lobsters are born bright blue.",
    "Cats can hear ultrasound.",
    "\"Goodbye\" came from \"God bye\" which came from \"God be with you.\"",
    "Avocados are a fruit, not a vegetable. They're technically considered a single-seeded berry, believe it or not.",
    /* "Dogs are WAY better then cats, no cap.", */
    "The shortest war in history lasted 38 to 45 minutes between Britain and Zanzibar in 1896.",
    "Octopuses have three hearts, nine brains, and blue blood.",
    "A group of flamingos is called a \"flamboyance.\"",
    "The unicorn is Scotland's national animal.",
    "Astronauts' height can change in space due to the absence of gravity compressing their spines.",
    "A day on Venus is longer than its year, as it takes Venus 225 Earth days to rotate and 243 Earth days to orbit the Sun.",
    "Strawberries aren't berries, but bananas are berries.",
    "In ancient Greece, throwing an apple to a woman was a marriage proposal.",
    "Honeybees can recognize human faces.",
    "The tongue is the strongest muscle in the human body relative to its size.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The average person walks the equivalent of five times around the world in a lifetime.",
    "Maine is the closest U.S. state to Africa.",
    "Armadillos are the only mammals that carry leprosy.",
    "The world's oldest known recipe is for beer.",
    "The Eiffel Tower can grow up to 6 inches taller in the summer due to thermal expansion.",
    "The \"D\" in D-Day stands for \"Day,\" and the \"H\" in H-hour stands for \"Hour.\"",
    "The name for the shape of Pringles is called a \"Hyperbolic Paraboloid.\"",
    "The first recorded game of baseball was played in 1846.",
    "A group of crows is called a \"murder.\"",
    "Humans share about 50% of their DNA with bananas.",
    "The average cloud weighs about 1.1 million pounds.",
    "The world's smallest mammal is the bumblebee bat.",
    "The longest hiccuping spree lasted for 68 years.",
    "A group of porcupines is called a prickle.",
    "The average person will spend six months of their life waiting for red lights to turn green.",
    "The word \"gorilla\" is derived from a Greek word meaning \"a tribe of hairy women.\"",
    "The oldest known living tree is over 5,000 years old.",
    "There's enough gold in the Earth's core to coat its entire surface in 1.5 feet of gold.",
    "Canadians say \"sorry\" so much that a law was passed in 2009 declaring that an apology can't be used as evidence of admission to guilt.",
    "Back when dinosaurs existed, there used to be volcanoes that were erupting on the moon.",
    "The only letter that doesn't appear on the periodic table is J.",
    "One habit of intelligent humans is being easily annoyed by people around them but saying nothing in order to avoid a meaningless argument.",
    "If a polar bear and a grizzly bear mate, their offspring is called a \"pizzy bear.\"",
    "In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola.",
    "The ten highest mountain summits in the United States are all located in Alaska.",
    "A single strand of Spaghetti is called a \"Spaghetto.\"",
    "In Colorado, USA, there is still an active volcano. It last erupted about the same time as the pyramids were being built in Egypt.",
    "The first movie ever to put out a motion-picture soundtrack was Snow White and the Seven Dwarfs.",
    "The scientific name for Giant Anteater is Myrmecophaga Tridactyla. This means \"ant eating with three fingers.\"",
    "The flashes of colored light you see when you rub your eyes are called \"phosphenes.\"",
    "At birth, a baby panda is smaller than a mouse.",
    "Iceland does not have a railway system.",
    "There is a company in Japan that has schools that teach you how to be funny. The first one opened in 1982. About 1,000 students take the course each year.",
    "The Roman-Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD.",
    "If you translate \"Jesus\" from Hebrew to English, the correct translation is \"Joshua.\" The name \"Jesus\" comes from translating the name from Hebrew to Greek to Latin to English.",
    "75% of the world's diet is produced from just 12 plants and five different animal species.",
    "The British government coined the slogan, \"Keep Calm and Carry on,\" during World War 2 in order to motivate citizens to stay strong. Posters with the slogan were printed but never officially issued, and were only unearthed in 2000.",
    "The largest Japanese population outside of Japan stands at 1.6 million people who live in Brazil.",
    "In 2009, Stephen Hawking held a reception for time travelers but didn't publicize it until after. This way, only those who could time travel would be able to attend. Nobody else attended.",
    "Nowadays, millionaires with just $1 million aren't considered wealthy anymore by most Americans. Now, the typical American sees at least $2.4 million as wealthy.",
    "Although GPS is free for the world to use, it costs $2 million per day to operate. The money comes from American tax revenue.",
    "In World War II, Germany tried to collapse the British economy by dropping millions of counterfeit bills over London.",
    "Until 2016, the \"Happy Birthday\" song was not for public use. Meaning that prior to 2016, the song was copyrighted, and you had to pay a license to use it.",
    "Lettuce is a member of the sunflower family.",
    "A wildlife technician, Richard Thomas, took the famous tongue twister, \"how much wood would a woodchuck chuck if a woodchuck could chuck wood\" and calculated a rough estimate of what the answer would actually be. It came out to be around 700 pounds.",
    "There are times when Pluto is closer to the Sun than Neptune - one of these timelines was from 1979 to 1999.",
    "The Ethiopian calendar is 7.5 years behind the Gregorian calendar due to the fact that it has 13 months.",
    "China is spending $3 billion dollars to build panda-shaped solar farms in order to get more young people interested in renewable energy.",
    "Mercury and Venus are the only two planets in our solar system that do not have any moons.",
    "The average American child is given $3.70 per tooth that falls out.",
    "If you heat up a magnet, it will lose its magnetism.",
    "More tornadoes occur in the United Kingdom per square mile than in any other country in the world.",
    "Times Square was originally called Longacre Square until it was renamed in 1904 after The New York Times moved its headquarters to the newly built Times Building.",
    "There is a statue of Tesla in Silicon Valley that radiates free Wi-Fi. It was done as an homage to his vision for wireless communication.",
    "500 seeds of 5 different types of seeds were taken into orbit around the moon and later planted around the U.S. as well as a few countries. They were called Moon Trees.",
    "Over 290 people have died climbing Mount Everest since 1922. Most deaths occur because of avalanches, and not all bodies have been recovered.",
    "A bolt of lightning can reach 53,540 degrees Fahrenheit. That's 5 times hotter than the surface of the sun, which is 10,340 degrees Fahrenheit.",
    "When Shakira was in second grade, she was rejected by the school choir because her vibrato was too strong. The music teacher told her that she sounded like a goat.",
    "Brain fibers lose 10% of their total length every decade. They can shrink even more so under acute stress.",
    "On one slow news day on April 18, 1930, a BBC radio announcer blatantly said, \"there is no news.\"",
    "There is over 3,000 characters that are commonly used in Japan (Japanese).",
    "There is an insurance policy issued against alien abduction. Around 50,000 policies have been sold, mainly to residents of the U.S. and England.",
    "Butterflies cannot fly if their body temperature is less than 86 degrees.",
    "Neurons multiply at a rate 250,000 neurons per minute during early pregnancy.",
    "Elephants have the longest pregnancy in the animal kingdom at 22 months. The longest human pregnancy on record is 17 months, 11 days.",
    "Dragonflies are capable of flying sixty miles per hour, making them one of the fastest insects. This is good since they are in a big hurry, as they only live about twenty-four hours.",
    "Flies jump backwards during takeoff.",
    "More people are afraid of spiders than death. Amazingly, few people are afraid of Champagne corks even though you are more likely to be killed by one than by a spider.",
    "Your brain consumes 25 watts of power while you're awake. This amount of energy is enough to illuminate a lightbulb.",
    "Intelligent people have more zinc and copper in their hair.",
    "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
    "The world's youngest parents were 8 and 9 and lived in China in 1910.",
    "Stephen Hawking was born exactly 300 years after Galileo died.",
    "Grapes explode when you put them in the microwave.",
    "Peanuts are one of the ingredients of dynamite.",
    "The average chocolate bar has 8 insects' legs in it.",
    "By raising your legs slowly and lying on your back, you cannot sink into quicksand.",
    "The glue on Israeli postage is certified kosher.",
    "The top butterfly flight speed is 12 miles per hour. Some moths can fly 25 miles per hour!",
    "14% of all facts and statistics are made up and 27% of people know that fact.",
    "Banging your head against a wall uses 150 calories an hour.",
    "U.S. Dollar bills are made out of cotton and linen.",
    "The dot over the letter \"i\" is called a tittle.",
    "40% of McDonald's profits come from the sales of Happy Meals.",
    "Every person, including identical twins, has a unique eye & tongue print along with their fingerprint.",
    "If you put a drop of liquor on a scorpion, it will instantly go mad and sting itself to death.",
    "IBM's motto is \"Think\". Apple later made their motto \"Think different\".",
    "You share your birthday with at least 9 million other people in the world.",
    "Each year in America there are about 300,000 deaths that can be attributed to obesity.",
    "About 55% of all movies are rated R.",
    "About 500 movies are made in the U.S. and 800 in India annually.",
    "There is actually no danger in swimming right after you eat, though it may feel uncomfortable.",
    "On a Canadian two-dollar bill, the American flag is flying over the Parliament Building.",
    "Rats and horses can't vomit.",
    "The catfish has over 27000 taste buds (more than any other animal).",
    "An ostrich's eye is bigger than its brain.",
    "11% of the world is left-handed.",
    "A healthy (non-colorblind) human eye can distinguish between 500 shades of gray.",
    "Elvis had a twin brother named Garon, who died at birth, which is why Elvis middle name was Aron.",
    "A jellyfish is 95% water.",
    "Common Cobra venom is not on the list of top 10 venoms yet it is still 40 times more toxic than cyanide.",
    "Truck driving is the most dangerous occupation by accidental deaths (799 in 2001).",
    "A dragonfly has a lifespan of 24 hours.",
    "A dime has 118 ridges around the edge. A quarter has 119.",
    "Abraham Lincoln's ghost is said to haunt the White House.",
    "Right handed people live, on average, nine years longer than left-handed people.",
    "Like fingerprints, everyone's tongue print is different!",
    "Women blink nearly twice as much as men.",
    "Coca-Cola would be green if coloring weren't added to it.",
    "It's against the law to burp, or sneeze in a church in Nebraska, USA.",
    "A man named Charles Osborne had the hiccups for 69 years!",
    "The Bible, the world's best-selling book, is also the world's most shoplifted book.",
    "A snail can sleep for three years.",
    "Pepsi originally contained pepsin, thus the name.",
    "The giant red star Betelgeuse has a diameter larger than that of the Earth's orbit around the sun.",
    "Maine is the only state (in USA) whose name is just one syllable.",
    "California consumes more bottled water than any other product.",
    "in Utah, it is illegal to swear in front of a dead person.",
    "Wyoming was the first state to give women the right to vote in 1869.",
    "Hawaii is the only coffee producing state.",
    /* "Gary, Indiana is the murder capital of the U.S. - probably the world.", */
    "In Quebec, there is an old law that states margarine must be a different color than butter.",
    "The world's oldest hotel has been operating since 705 A.D.",
    "The word \"tragedy\" comes from an ancient Greek word meaning \"goat song\"",
    "Penguins Used to be six feet tall.",
    "At any given moment, there are approximately 2,000 thunderstorms happening on Earth.",
    "A million Earths would fit inside the Sun.",
    "There are 10 different ways to pronounce the letters \"Ough\"",
    "Doctors who play video games more than three hours a week make fewer operating room errors.",
    "A sneeze sounds different around the world.",
    "Picasso was a suspect in the 1911 Mona Lisa theft.",
    "The record lowest temperature in the U.S. was -80°F",
    "Cheese may prevent nightmares.",
    "It's illegal to sell photos of the Eiffel Tower at night.",
    "A shrimp's heart is in its head.",
    "The Earth weighs about 13,170,000,000,000,000,000,000,000 pounds.",
    "\"Aviation English\" is the language all pilots must speak, no matter what nationality they are.",
    "The original Shortcuts started in 2014 and was called Workflow.",
    "Human teeth are the only part of the body that cannot heal themselves.",
    "The heart of a shrimp is located in its head.",
    "People are more creative in the shower.",
    "A 73-year-old bottle of French Burgundy became the most expensive bottle of wine ever sold at auction in 2018, going for $558,000.",
    "A jiffy is an actual unit of time. It's 1/100th of a second.",
    "Everyone's tongue print is different. Like the fingerprint, it has unique features that differ from person to person.",
    "It would take 19 minutes to fall to the centre of the Earth.",
    "There are more than 1,000 types of bananas growing in the world.",
    "Humans are the only animals that blush.",
    "Vatican City is the smallest country in the world. It's 120 times smaller than the island of Manhattan.",
    "Japan has over 200 flavours of Kit Kats. They're exclusively created for different regions, cities, and seasons.",
    "In the course of an average lifetime, while sleeping you could eat around 70 different insects and 10 spiders, or more.",
    "Dolphins have names for one another. According to National Geographic, dolphins use a unique whistle to distinguish between different members in their pod.",
    "Three presidents, all Founding Fathers - John Adams, Thomas Jefferson, and James Monroe - died on July 4.",
    "There actually aren't \"57 varieties\" of Heinz ketchup, and never were. Company founder H.J. Heinz thought his product should have a number, and he liked 57.",
    "In 2010, Microsoft held a funeral for the iPhone and BlackBerry after they thought the Windows Phone 7 would beat the market.",
    "Q-tip cotton swabs were originally called \"baby gays.\"",
    "In a day 34,000 children die every day from causes that are related to poverty and hunger.",
    "Indonesia consists only of islands - 13,667 total.",
    "During World War II, the very first bomb dropped on Berlin by the Allies killed the only elephant in the Berlin Zoo.",
    "People who ride on roller coasters have a higher chance of having a blood clot in the brain.",
    "The tallest freestanding sculpture in the world is Chief Crazy Horse in South Dakota, USA.",
    "Marie Curie, the Nobel prize winning scientist who discovered radium, died of radiation poisoning.",
    "898 tornadoes were recorded to have occurred in the United States in the year 2000.",
    "The word Popcorn is derived from the middle English word \"poppe,\" which means \"explosive sound\"",
    "The food that is digested in your stomach is called \"chyme.\"",
    "Alcohol beverages have all 13 minerals necessary for human life.",
    "The sentence \"The quick brown fox jumps over the lazy dog.\" uses every letter in the alphabet (developed by Western Union to Test telex/twxcommunications).",
    "The word housekeeping was invented by Shakespeare.",
    "The only two days of the year in which there are no professional sports games (MLB, NBA, NHL, or NFL) are the day before and the day after the Major League All-Star Game.",
    "In the great fire of London in 1666 half of London was burnt down but only 6 people were injured.",
    "Lack of sleep can affect your immune system and reduce your ability to fight infections.",
    "All dogs are the descendant of the wolf. These wolves lived in eastern Asia about 15,000 years ago.",
    "It is not possible to tickle yourself. The cerebellum, a part of the brain, warns the rest of the brain that you are about to tickle yourself. Since your brain knows this, it ignores the resulting sensation",
    "Parma ham is only Parma ham if it is made in the Parma region of Italy. The British chain supermarket Asda, made and packaged its own \"Parma ham\" and was successfully sued by the real Parma ham people (Parma Ham Trade Association)",
    "With winds of 50 miles per hour, The Statue of Liberty sways three inches and the torch sways five inches.",
    "A famous bullfighter, Lagarijo, killed 4,867 bulls in the 19th century.",
    "Police detectives have used snapping turtles to help them locate dead bodies.",
    "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
    "The national sport of Japan is sumo wrestling.",
    "The early occurrence of a fetus yawning is at eleven weeks after conception.",
    "In a month, a fingernail grows an eighth of an inch.",
    "Edward VIII did not officially become the King of England as he abdicated the throne to marry an American divorcee.",
    "The book \"Little Red Riding Hood\" was banned in 1990 by two school districts in California. They did this because in the book there was a picture of a basket that had a bottle of wine in it",
    "The reason why golf balls have dimples on them is because it helps in the ball to move a farther distance by reducing drag.",
    "Americans consume the most peanut butter in the world.",
    "Celtic warriors sometimes fought their battles naked, their bodies dyed blue from head to toe.",
    "To make butter more attractive in colour, carrot juice was used by people in the Middle Ages.",
    "Early hockey games allowed as many as 30 players a side on the ice.",
    "Most fleas do not live past a year old.",
    "It takes seven to ten days to make a jelly belly jellybean.",
    "Some asteroids have other asteroids orbiting them.",
    "Maine is the only state whose name is just one syllable.",
    "Every second, 8000 Coca-Cola Company products are consumed in the world.",
    "All babies are colour blind when they are born.",
    "There are approximately 9,000 taste buds on the tongue.",
    "Most heart attacks occur between the hours of 8 and 9 am.",
    "Smelling bananas can help a person lose weight.",
    "In the U.S., the sport that causes the most injuries among the age group of 15-24 is basketball.",
    "The only nation whose name begins with an \"A\", but doesn't end in an \"A\" is Afghanistan.",
    "Cats urine glows under a black light.",
    "Rhode Island is the only state which the hammer throw is a legal high school sport.",
    "The top 3 health-related searches on the Internet are (in this order): Depression, Allergies, & Cancer.",
    "Rubber bands last longer when refrigerated.",
    "Every time you lick a stamp, you consume 1/10 of a calorie.",
    "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first-class.",
    "WWII fighter pilots in the South Pacific armed their airplanes while stationed with .50 caliber machine gun ammo belts measuring 27 feet before being loaded into the fuselage. If the pilots fired all their ammo at a target, he went through \"the whole 9 yards\", hence the term.",
    "The Pentagon, in Arlington, Virginia, has twice as many bathrooms as is necessary, because when it was built in the 1940s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.",
    "The word \"dexter\" whose meaning refers to the right hand is typed with only the left hand.",
    "There is a town in Newfoundland, Canada called Dildo.",
    "The KGB is headquartered at No. 2 Felix Dzerzhinsky Square, Moscow.",
    "To \"testify\" was based on men in the Roman court swearing to a statement made by swearing on their testicles.",
    "Tigers not only have striped fur, they have striped skin!",
    "The 3 most valuable brand names on earth are Marlboro, Coca-Cola, and Budweiser (in that order).",
    "Approximately every seven minutes of every day, someone in an aerobics class pulls their hamstring.",
    "'Stewardesses' is the longest word that is typed with only the left hand.",
    "A piece of paper can be folded no more than 9 times.",
    "The site with the highest number of women visitors between the age of 35 and 44 years old: Alka-Seltzer.com.",
    "The world record for spitting a watermelon seed is 65 feet 4 inches.",
    "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
    "Some lions mate over 50 times a day.",
    "The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes.",
    "400-quarter pounders can be made from 1 cow.",
    "Napoleon's penis was sold to an American urologist for $40,000.",
    "It is illegal to hunt camels in the state of Arizona.",
    "Half of all Americans live within 50 miles of their birthplace.",
    "Texas is also the only state that is allowed to fly its state flag at the same height as the U.S. flag.",
    "The the U.S. you dial 911. In Stockholm, Sweden you dial 90000.",
    "Golf courses cover 4% of North America.",
    "Seattle's Fremont Bridge rises up and down more than any drawbridge in the world.",
    "Only female mosquito's' bite and most are attracted to the color blue twice as much as to any other color.",
    "Larry Lewis ran the 100-yard dash in 17.8 seconds in 1969, thereby setting a new world's record for runners in the 100-years-or-older class. He was 101.",
    "A rainbow can be seen only in the morning or late afternoon. It can occur only when the sun is 40 degrees or less above the horizon.",
    "The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.",
    "It is illegal to eat oranges while bathing in California.",
    "60% of electrocutions occur while talking on the telephone during a thunderstorm.",
    "The very first bomb dropped by the Allies on Berlin during World War II killed the only elephant in the Berlin Zoo.",
    "A giraffe can go without water longer than a camel.",
    "The very first song played on MTV was 'Video Killed The Radio Star' by the Buggles.",
    "Giraffes have no vocal cords.",
    "The first automobile race ever seen in the United States was held in Chicago in 1895. The track ran from Chicago to Evanston, Illinois. The winner was J. Frank Duryea, whose average speed was 71/2 miles per hour.",
    "Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.",
    "The average person falls asleep in seven minutes.",
    "The word Pennsylvania is misspelled on the Liberty Bell.",
    "The longest word comprised of one row on the keyboard is: TYPEWRITER.",
    "Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.",
    "Bats always turn left when exiting a cave.",
    "In space, astronauts are unable to cry, because there is no gravity and the tears won't flow.",
    "In Bangladesh, kids as young as 15 can be jailed for cheating on their finals!",
    "111,111,111 x 111,111,111 = 12,345,678,987,654,321.",
    "Starfish haven't got brains.",
    "There are 1,575 steps from the ground floor to the top of the Empire State building.",
    "No word in the English language rhymes with month, orange, silver and purple.",
    "On average, Americans' favorite smell is banana.",
    "More Monopoly money is printed in a year, than real money throughout the world.",
    "The following sentence: 'A rough-coated, dough-faced, thoughtful ploughman strode through the streets of Scarborough; after falling into a slough, he coughed and hiccoughed.' Contains the nine different pronunciations of \"ough\" in the English Language.",
    "The only two days of the year in which there are no professional sports games--MLB, NBA, NHL, or NFL--are the day before and the day after the Major League All-Star Game.",
    "Poland is the \"stolen car capital of the world\".",
    "Cats have over one hundred vocal sounds, while dogs only have about ten.",
    "In 1912 a law passed in Nebraska where drivers in the country at night were required to stop every 150 yards, send up a skyrocket, wait eight minutes for the road to clear before proceeding cautiously, all the while blowing their horn and shooting off flares.",
    "Non-dairy creamer is flammable.",
    "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
    "You can't kill yourself by holding your breath.",
    "Daylight Saving Time is not observed in most of the state of Arizona and parts of Indiana.",
    "The letters KGB stand for Komitet Gosudarstvennoy Bezopasnosti.",
    "Researchers at the Texas Department of Highways in Fort Worth determined the cow population of the U.S. burps some 50 million tons of valuable hydrocarbons into the atmosphere each year. The accumulated burps of ten average cows could keep a small house adequately heated and its stove operating for a year.",
    "When possums are playing 'possum', they are not \"playing.\" They actually pass out from sheer terror.",
    "When a Hawaiian woman wears a flower over her left ear, it means that she is not available.",
    "Half the foods eaten throughout the world today were developed by farmers in the Andes Mountains (including potatoes, maize, sweet potatoes, squash, all varieties of beans, peanuts, manioc, papayas, strawberries, mulberries and many others).",
    "Blueberry Jelly Bellies were created specifically for Ronald Reagan.",
    "Mount Olympus on Mars is three times the size of Mount Everest.",
    "A cat has 32 muscles in each ear.",
    "Einstein couldn't speak fluently until after his ninth birthday. His parents thought he was mentally retarded.",
    "Barbie's measurements, if she were life-size, would be 39-29-33.",
    "Conception occurs most in the month of December.",
    "In a lifetime the average human produces enough quarts of spit to fill 2 swimming pools.",
    "Most dust particles in your house are made from dead skin.",
    "The only real person to ever to appear on a pez dispenser was Betsy Ross.",
    "The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.",
    "In the last 4000 years, no new animals have been domesticated.",
    "The word \"samba\" means \"to rub navels together.\"",
    "A pregnant goldfish is called a twit.",
    "Los Angeles' full name 'El Pueblo de Nuestra Senora la Reina de Los Angeles de Porciuncula' is reduced to 3.63% of its size in the abbreviation 'L.A.'.",
    "A pig's orgasm lasts for 30 minutes.",
    "Coca-Cola was originally green.",
    "The average talker sprays about 300 microscopic saliva droplets per minute, about 2.5 droplets per word.",
    "If we had the same mortality rate now as in 1900, more than half the people in the world today would not be alive.",
    "In Vermont, the ratio of cows to people is 10:1.",
    "The average American looks at eight houses before buying one.",
    "Shakespeare is quoted 33,150 times in the Oxford English dictionary.",
    "The most common street name in the U.S. is Second Street.",
    "The Black Widow spider eats her mate during or after sex.",
    "It was discovered on a space mission that a frog can throw up. The frog throws up its stomach first, so the stomach is dangling out of its mouth. Then the frog uses its forearms to dig out all of the stomach's contents and then swallows the stomach back down.",
    "A person cannot taste food unless it is mixed with saliva. For example, if a strong-tasting substance like salt is placed on a dry tongue, the taste buds will not be able to taste it. As soon as a drop of saliva is added and the salt is dissolved, however, a definite taste sensation results. This is true for all foods.",
    "A horse can look forward with one eye and back with the other.",
    "The name Jeep came from the abbreviation used in the army. G.P. for 'General Purpose' vehicle.",
    "Mozart wrote the nursery rhyme 'twinkle, twinkle, little star' at the age of 5.",
    "The world's record for keeping a Lifesaver in the mouth with the hole intact is 7 hrs 10 min.",
    "There are 293 ways to make change for a dollar.",
    "The name of the girl on the statue of liberty is Mother of Exiles.",
    "Iceland consumes more Coca-Cola per capita than any other nation.",
    "The longest one-syllable word in the English language is \"screeched.\"",
    "Some individuals express concern sharing their soap, rightly so, considering 75% of all people wash from top to bottom.",
    "The human heart creates enough pressure to squirt blood 30ft.",
    "Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning \"containing arsenic.\"",
    "The average person's left hand does 56% of the typing.",
    "The first CD pressed in the U.S. was Bruce Springsteen's 'Born in the USA.'",
    "A standard slinky measures 87 feet when stretched out.",
    "The placement of a donkey's eyes in its' heads enables it to see all four feet at all times!",
    "All of the clocks in the movie \"Pulp Fiction\" are stuck on 4:20, a national pot-smokers hour.",
    "The strongest muscle (Relative to size) in the body is the tongue.",
    "Since 1978, 37 people have died by Vending Machine's falling on them. 13 people are killed annually. All this while trying to shake merchandise out of them. 113 people have been injured.",
    "Average life span of a major league baseball: 7 pitches.",
    "You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.",
    "When you sneeze, air and particles travel through the nostrils at speeds over100 mph. During this time, all bodily functions stop, including your heart, contributing to the impossibility of keeping one's eyes open during a sneeze.",
    "Pearls melt in vinegar.",
    "Venus is the only planet that rotates clockwise.",
    "A jellyfish is 95 percent water!",
    "Leonardo Da Vinci could write with one hand while drawing with the other.",
    "In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.",
    "Lorne Greene had one of his nipples bitten off by an alligator while he was host of \"Lorne Greene's Wild Kingdom.\"",
    "10,000 Dutch cows pass through the Amsterdam airport each year.",
    "In Miconesia, coins are 12 feet across.",
    "The heart beats about 100,000 times per day.",
    "The average person spends about six months of their life waiting for red lights to turn green.",
    "Avocados are a fruit, not a vegetable.",
    "One-fourth of the world's population lives on less than $200 a year. Ninety million people survive on less than $75 a year.",
    "All polar bears are left-handed.",
    "If a rooster can't fully extend its neck, it can't crow.",
    "There are 336 dimples on a regulation golf ball.",
    "When the French Academy was preparing its first dictionary, it defined \"crab\" as, \"A small red fish, which walks backwards.\" This definition was sent with a number of others to the naturalist Cuvier for his approval. The scientist wrote back, \"Your definition, gentlemen, would be perfect, only for three exceptions. The crab is not a fish, it is not red and it does not walk backwards.\"",
    "NBA superstar Michael Jordan was originally cut from his high school basketball team.",
    "Former basketball superstar Michael Jordan is the most recognized face in the world, more than the pope himself.",
    "On an American one-dollar bill, there is an owl in the upper left-hand corner of the \"1\"encased in the \"shield\" and a spider hidden in the front upper right-hand corner.",
    "Two-thirds of the world's eggplant is grown in New Jersey.",
    "Leonardo Da Vinci invented the scissors.",
    "The longest word in the English language, according to the Oxford English Dictionary, is pneumonoultramicroscopicsilicovolcanoconiosis.",
    "The first song played on Armed Forces Radio during operation Desert Shield was \"Rock the Casba\" by the Clash.",
    "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
    "Daffy Duck's middle name is \"Dumas\"",
    "Every acre of American crops harvested contains 100 pounds of insects.",
    "Only one person in two billion will live to be 116 or older.",
    "A literal translation of a standard traffic sign in China: \"Give large space to the festive dog that makes sport in the roadway.\"",
    "Lawn darts are illegal in Canada.",
    "Crocodiles and alligators are surprisingly fast on land. Although they are rapid, they are not agile. So, if being chased by one, run in a zigzag line to lose him or her.",
    "Kinder Surprise eggs are actually illegal in the United States.",
    "Apache servers send a status code 218 for certain errors, even though anything that starts with a 2 is suppost to mean success.",
    "The city of Cleveland, Ohio holds the world record for the most balloons released at one time ever, in total, releasing 1.5 million balloons.",
    "The most viewed video on YouTube is Baby Shark by Pingfong.",
    "There was a time where Internet Explorer was the default MacOS web browser and, in return, microsoft made office for Mac and invested $150 million in Apple.",
    "The most common birthday is September 9th, meanwhile the least common birthday is December 25th or February 29th (only happens on leap years).",
    "Both volleyball and basketball were invented in Massachusetts.",
    /* "The United States school system was designed to produce obedient factory workers, rather than to educate people.", */
    /* "Homework was invented as a punishment for people who did not do their work.", */
    /* "To this day, in the United States, slavery is still completely legal in prisons.", */
    "Wombat poop is cube-shaped to prevent it from rolling away.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Your nose can remember up to 50,000 different scents.",
    "There are more possible games of chess than atoms in the observable universe.",
    "Sharks are older than trees by about 50 million years.",
    "Antarctica is the world's largest desert, not the Sahara.",
    "A group of ravens is called an unkindness.",
    "The shortest commercial flight in the world is 57 seconds long.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
    "Your brain uses 20% of your body's total energy despite being only 2% of your body weight.",
    "Lobsters were once considered poor people's food and were fed to prisoners.",
    "The Great Wall of China contains rice as one of its binding ingredients.",
    "A crocodile cannot stick its tongue out.",
    "The human brain has approximately 86 billion neurons.",
    "Polar bears have black skin underneath their white fur.",
    "Oxford University is older than the Aztec Empire.",
    "A day on Mercury is longer than its year.",
    "The word 'set' has the most different meanings in English.",
    "Butterflies taste with their feet.",
    "The human eye can distinguish between 10 million different colors.",
    "Bees can fly higher than Mount Everest.",
    "A group of owls is called a parliament.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "Mushrooms are more closely related to humans than to plants.",
    "The speed of light is exactly 299,792,458 meters per second.",
    "Koalas sleep up to 22 hours per day.",
    "Russia spans 11 time zones.",
    "The longest word you can type using only your left hand is 'stewardesses'.",
    "Seahorses are the only animals where males give birth.",
    "A group of hedgehogs is called a prickle.",
    "The Moon is moving away from Earth at a rate of 1.5 inches per year.",
    "Sloths only defecate once a week.",
    "The first webcam was created to monitor a coffee pot.",
    "Bananas are radioactive due to their potassium content.",
    "A jiffy is an actual unit of time equal to 1/100th of a second.",
    "Pineapples take two years to grow.",
    "The human stomach gets entirely new lining every 3-5 days.",
    "There are more ways to arrange a deck of cards than there are atoms on Earth.",
    "Dolphins have names for each other.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "Platypuses are one of the only venomous mammals.",
    "The strongest muscle in the human body is the masseter (jaw muscle).",
    "A group of pugs is called a grumble.",
    "Glass takes one million years to decompose.",
    "The longest hiccuping fit lasted 68 years.",
    "Elephants can hear through their feet.",
    "The shortest war lasted only 38-45 minutes.",
    "A bolt of lightning is five times hotter than the surface of the Sun.",
    "Penguins have an organ above their eyes that converts seawater to freshwater.",
    "The human brain is 75% water.",
    "Dragonflies have been around for 300 million years.",
    "A group of jellyfish is called a smack.",
    "The loudest bone in your body is your eardrum.",
    "Trees can communicate with each other through underground networks.",
    "The probability of shuffling a deck of cards into the same order twice is virtually zero.",
    "Cats have a third eyelid called a nictitating membrane.",
    "The human body contains enough iron to make a 3-inch nail.",
    "The word 'almost' is the longest word with all letters in alphabetical order.",
    "A shrimp's heart is in its head.",
    "There are more bacteria in your mouth than people on Earth.",
    "The human skeleton completely replaces itself every 10 years.",
    "A day on Venus is equivalent to 243 Earth days.",
    "The oldest known living organism is a mushroom in Oregon that's 2,400 years old.",
    "Hippos produce pink milk.",
    "The human nose can detect over 1 trillion different scents.",
    "A group of pandas is called an embarrassment.",
    "The Earth's core is as hot as the surface of the Sun.",
    "Chickens can live for weeks without their heads.",
    "The word 'rhythm' is the longest English word without a vowel.",
    "Sea otters hold hands while sleeping to prevent drifting apart.",
    "The human body produces 25 million new cells every second.",
    "The tongue is the only muscle attached at only one end.",
    "Honey bees can recognize human faces.",
    "The human heart beats about 100,000 times per day.",
    "A sneeze travels at about 100 miles per hour.",
    "Fingernails grow four times faster than toenails.",
    "A group of unicorns is called a blessing.",
    "The human eye blinks about 17,000 times per day.",
    "Kangaroos cannot walk backward.",
    "The average person walks past 36 murderers in their lifetime.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "The human brain can process information as fast as 120 meters per second.",
    "Crows can remember human faces for years.",
    "The longest recorded time without sleep is 264 hours.",
    "A group of rhinos is called a crash.",
    "The human stomach can stretch to hold about 1 liter of food.",
    "Hummingbirds are the only birds that can fly backward.",
    "The speed of a computer mouse is measured in 'mickeys'.",
    "A group of baboons is called a congress.",
    "The human brain is more active during dreams than when awake.",
    "Bees communicate through dancing.",
    "The longest word in the English language has 189,819 letters.",
    "A group of cobras is called a quiver.",
    "The human body is about 60% water.",
    "Giraffes only need 5-30 minutes of sleep per day.",
    "The average person spends 5 years of their life eating.",
    "A group of starfish is called a galaxy.",
    "The human liver can regenerate itself completely.",
    "Mosquitoes are attracted to people who have recently eaten bananas.",
    "The largest snowflake ever recorded was 15 inches wide.",
    "A group of turtles is called a bale.",
    "The human brain weighs about 3 pounds.",
    "Camels have three eyelids to protect against sand storms.",
    "The average person produces enough saliva to fill two swimming pools in their lifetime.",
    "A group of leopards is called a leap.",
    "The human heart is about the size of a fist.",
    "Owls cannot move their eyes in their sockets.",
    "The fastest recorded sneeze was 165 kilometers per hour.",
    "A group of sharks is called a shiver.",
    "The human body has 206 bones.",
    "Mantis shrimps can see 16 types of color receptors (humans have only 3).",
    "The average person laughs 13 times per day.",
    "A group of apes is called a shrewdness.",
    "The human lung has 300 million air sacs called alveoli.",
    "Woodpeckers' tongues wrap around their skulls.",
    "The coldest temperature ever recorded was -128.6°F in Antarctica.",
    "A group of locusts is called a plague.",
    "The human body contains 37.2 trillion cells.",
    "Flamingos can only eat with their heads upside down.",
    "The average person blinks 15-20 times per minute.",
    "A group of peacocks is called a muster.",
    "The human digestive system is about 30 feet long.",
    "Spiders recycle their webs by eating them.",
    "The hottest temperature ever recorded was 134°F in Death Valley.",
    "A group of eagles is called a convocation.",
    "The human kidney filters about 120-150 quarts of blood daily.",
    "Ants can lift 50 times their own body weight.",
    "The average person breathes 20,000 times per day.",
    "A group of stingrays is called a fever.",
    "The human tongue has about 10,000 taste buds.",
    "Penguins can jump 6 feet out of water.",
    "The most struck-by-lightning person was struck 7 times and survived.",
    "A group of cats is called a clowder.",
    "The human ear can hear sounds from 20 Hz to 20,000 Hz.",
    "Rats laugh when tickled.",
    "The average person dreams for 2 hours every night.",
    "A group of whales is called a pod.",
    "The human skin sheds about 8 pounds of dead cells annually.",
    "Chameleons' tongues are twice the length of their body.",
    "The smallest bone in the human body is in the ear.",
    "A group of fish is called a school.",
    "The human small intestine is about 20 feet long.",
    "Bats are the only mammals capable of sustained flight.",
    "The average person yawns 5-10 times per day.",
    "A group of wolves is called a pack.",
    "The human bladder can hold about 16 ounces of urine.",
    "Snails can sleep for up to 3 years.",
    "The longest place name has 85 letters and is in New Zealand.",
    "A group of geese is called a gaggle.",
    "The human appendix may help maintain gut bacteria.",
    "Hummingbirds weigh less than a penny.",
    "The average person hiccups for 68 years of their life.",
    "A group of horses is called a herd.",
    "The human esophagus is about 10 inches long.",
    "Goldfish have a memory span of months, not seconds.",
    "The deepest point in the ocean is 36,200 feet deep.",
    "A group of cows is called a herd.",
    "The human gallbladder stores bile from the liver.",
    "Cheetahs cannot roar, only purr and chirp.",
    "The tallest tree in the world is 379 feet tall.",
    "A group of deer is called a herd.",
    "The human spleen filters old blood cells.",
    "Alligators can live up to 100 years.",
    "The largest living organism is a fungus in Oregon.",
    "A group of elephants is called a herd.",
    "The human thyroid regulates metabolism.",
    "Butterflies migrate thousands of miles.",
    "The oldest known musical instrument is 40,000 years old.",
    "A group of lions is called a pride.",
    "The human pancreas produces insulin.",
    "Arctic foxes change color with the seasons.",
    "The largest desert in Asia is the Gobi Desert.",
    "A group of bears is called a sleuth.",
    "The human adrenal glands produce adrenaline.",
    "Polar bears are nearly undetectable by infrared cameras.",
    "The longest river in the world is the Nile at 4,132 miles.",
    "A group of monkeys is called a troop.",
    "The human pituitary gland controls other glands.",
    "Hummingbirds' hearts beat 1,260 times per minute.",
    "The oldest continuously inhabited city is Damascus, Syria.",
    "A group of birds is called a flock.",
    "The human pineal gland produces melatonin.",
    "Seahorses' eyes move independently of each other.",
    "The driest place on Earth is the Atacama Desert.",
    "A group of sheep is called a flock.",
    "The human thymus gland shrinks with age.",
    "Parrots can live over 100 years.",
    "The highest waterfall in the world is Angel Falls at 3,212 feet.",
    "A group of ants is called a colony.",
    "The human parathyroid glands regulate calcium.",
    "Turtles can breathe through their butts.",
    "The smallest country in the world is Vatican City.",
    "A group of bees is called a swarm.",
    "The human tonsils help fight infections.",
    "Otters have the densest fur in the animal kingdom.",
    "The largest lake in the world is the Caspian Sea.",
    "A group of butterflies is called a kaleidoscope.",
    "The human bone marrow produces blood cells.",
    "Cuttlefish can change color instantly.",
    "The coldest inhabited place is Oymyakon, Russia at -96.16°F.",
    "A group of dolphins is called a pod.",
    "The human lymph nodes filter lymph fluid.",
    "Sloths move so slowly that algae grows on them.",
    "The largest glacier is Lambert Glacier in Antarctica.",
    "A group of penguins is called a colony.",
    "The human vocal cords vibrate to produce sound.",
    "Mules are a cross between horses and donkeys and are usually sterile.",
    "The highest mountain in the solar system is on Mars.",
    "A group of seals is called a pod.",
    "The human diaphragm helps with breathing.",
    "Jaguars have the strongest bite force of any big cat.",
    "The largest canyon in the solar system is on Mars.",
    "A group of otters is called a raft.",
    "The human epiglottis prevents food from entering the windpipe.",
    "Axolotls can regenerate entire limbs.",
    "The deepest lake in the world is Lake Baikal in Russia.",
    "A group of meerkats is called a mob.",
    "The human uvula helps with speech and swallowing.",
    "Flamingos get their pink color from eating shrimp.",
    "The largest island in the world is Greenland.",
    "A group of kangaroos is called a mob.",
    "The human coccyx is a remnant of our ancestral tail.",
    "Peacock mantis shrimps have the fastest punch in the animal kingdom.",
    "The saltiest sea in the world is the Red Sea.",
    "A group of zebras is called a dazzle.",
    "The human hyoid bone is the only bone not connected to another bone.",
    "Tardigrades can survive in space.",
    "The longest mountain range is the Mid-Atlantic Ridge underwater.",
    "A group of giraffes is called a tower.",
    "The human atlas vertebra supports the skull.",
    "Emperor penguins can dive 1,800 feet deep.",
    "The windiest place on Earth is Commonwealth Bay, Antarctica.",
    "A group of hippos is called a bloat.",
    "The human sacrum is made of five fused vertebrae.",
    "Hummingbirds are the only birds that can hover in mid-air.",
    "The wettest place on Earth is Mount Waialeale in Hawaii.",
    "A group of crocodiles is called a bask.",
    "The human sternum protects the heart and lungs.",
    "Chimpanzees share 98.8% of their DNA with humans.",
    "The most lightning-struck place is Lake Maracaibo, Venezuela.",
    "A group of alligators is called a congregation.",
    "The human patella is the kneecap.",
    "Electric eels can generate 860 volts of electricity.",
    "The foggiest place on Earth is Grand Banks, Newfoundland.",
    "A group of lemurs is called a conspiracy.",
    "The human fibula is the smaller bone in the lower leg.",
    "Archerfish can shoot water jets to knock insects into the water.",
    "The sunniest place on Earth is Yuma, Arizona.",
    "A group of raccoons is called a gaze.",
    "The human ulna is one of the two bones in the forearm.",
    "Leafy sea dragons look exactly like seaweed.",
    "The rainiest place on Earth is Mawsynram, India.",
    "A group of squirrels is called a scurry.",
    "The human radius is the other bone in the forearm.",
    "Pistol shrimps create cavitation bubbles that reach 4,700°C.",
    "The snowiest place on Earth is Mount Rainier, Washington.",
    "A group of foxes is called a skulk.",
    "The human tibia is the larger bone in the lower leg.",
    "Honeypot ants store honey in their abdomens for the colony.",
    "The cloudiest place on Earth is Ben Nevis, Scotland.",
    "A group of bats is called a colony.",
    "The human femur is the longest bone in the body.",
    "Bombardier beetles spray boiling chemicals at attackers.",
    "The clearest water in the world is in the Blue Lake, New Zealand.",
    "A group of rats is called a mischief.",
    "The human humerus is the bone in the upper arm.",
    "Vampire bats are the only mammals that feed exclusively on blood.",
    "The most polluted city in the world is Kanpur, India.",
    "A group of mice is called a nest.",
    "The human scapula is the shoulder blade.",
    "Star-nosed moles can identify and eat prey in 230 milliseconds.",
    "The least polluted city in the world is Honolulu, Hawaii.",
    "A group of rabbits is called a warren.",
    "The human clavicle is the collarbone.",
    "Leafcutter ants don't eat leaves; they use them to grow fungus.",
    "The oldest living tree is a Great Basin bristlecone pine at 4,851 years old.",
    "A group of opossums is called a passel.",
    "The human mandible is the lower jaw bone.",
    "Bioluminescent mushrooms glow in the dark.",
    "The tallest mountain underwater is Mauna Kea in Hawaii.",
    "A group of armadillos is called a roll.",
    "The human maxilla is the upper jaw bone.",
    "Venus flytraps can count to five.",
    "The largest flower in the world can weigh up to 15 pounds.",
    "A group of skunks is called a surfeit.",
    "The human temporal bone houses the inner ear.",
    "Sensitive plants close their leaves when touched.",
    "The smallest flower in the world is smaller than a pinhead.",
    "The human parietal bone forms the sides of the skull.",
    "Resurrection plants can survive without water for years.",
    "The oldest seed to successfully germinate was 32,000 years old.",
    "A group of badgers is called a cete.",
    "The human frontal bone forms the forehead.",
    "Welwitschia plants can live over 1,000 years in the desert.",
    "The fastest-growing plant is bamboo, which can grow 35 inches in one day.",
    "A group of otters on land is called a romp.",
    "The human occipital bone forms the back of the skull.",
    "Titan arum flowers smell like rotting flesh to attract flies.",
    "The largest seed in the world weighs up to 40 pounds.",
    "A group of ferrets is called a business.",
    "The human sphenoid bone is deep inside the skull.",
    "Sundew plants use sticky droplets to catch insects.",
    "The oldest tree species still alive is the Ginkgo biloba.",
    "A group of weasels is called a pack.",
    "The human ethmoid bone helps form the nasal cavity.",
    "Lithops plants look exactly like stones.",
    "The deepest plant roots can extend 230 feet underground.",
    "A group of moles is called a labour.",
    "The human nasal bone forms the bridge of the nose.",
    "Dragon's blood trees look like giant umbrellas.",
    "The largest leaves in the world can be 25 feet long.",
    "A group of hedgehogs is called an array.",
    "The human lacrimal bone is the smallest facial bone.",
    "Baobab trees can store 32,000 gallons of water in their trunk.",
    "The smallest tree in the world is only 2 inches tall.",
    "A group of shrews is called a nest.",
    "The human palatine bone helps form the roof of the mouth.",
    "Strangler figs grow around other trees and eventually kill them.",
    "The poisonous tree that can blind you is the manchineel tree.",
    "A group of chinchillas is called a herd.",
    "The human zygomatic bone is the cheekbone.",
    "Telegraph plants move their leaves like they're dancing.",
    "The tree with the thickest trunk can be 119 feet in diameter.",
    "A group of guinea pigs is called a herd.",
    "The human vomer bone helps form the nasal septum.",
    "Sensitive ferns curl up when you touch them.",
    "The most dangerous plant in the world is the castor oil plant.",
    "A group of hamsters is called a horde.",
    "The human inferior nasal concha helps with breathing.",
    "Mimosa Pudica leaves close when touched or shaken.",
    "The most expensive spice in the world is saffron.",
    "A group of capybaras is called a herd.",
    "The human hyoid is the only bone that doesn't touch another bone.",
    "Duckweed is the fastest-growing flowering plant.",
    "The rarest flower in the world is the Middlemist's Red camellia.",
    "A group of prairie dogs is called a coterie.",
    "The human middle ear contains the three smallest bones.",
    "Pitcher plants digest insects that fall into them.",
    "The corpse flower blooms only once every 7-10 years.",
    "A group of woodchucks is called a fall.",
    "The human ear has 14 bones in total.",
    "Cobra plants snap shut to trap insects inside.",
    "The chocolate cosmos flower smells like chocolate.",
    "A group of groundhogs is called a coterie.",
    "The human skull has 22 bones in total.",
    "Bladderworts are underwater plants that suck in prey.",
    "The bee orchid looks exactly like a female bee.",
    "A group of beavers is called a colony.",
    "The human spine has 26 bones including the sacrum and coccyx.",
    "Resurrection moss can survive being completely dried out.",
    "The monkey face orchid looks like a monkey's face.",
    "A group of muskrats is called a nest.",
    "The human rib cage has 24 ribs in total.",
    "Desert roses are rocks that look like flowers.",
    "The naked man orchid looks like tiny naked men.",
    "A group of nutrias is called a nest.",
    "The human hand has 27 bones in total.",
    "Living stones plants look exactly like rocks.",
    "The dancing girls orchid looks like dancing figures.",
    "A group of chipmunks is called a scurry.",
    "The human foot has 26 bones in total.",
    "Silver torch cactus glows silver in moonlight.",
    "The dove orchid looks like a white dove in flight.",
    "A group of gophers is called a nest.",
    "The human arm has 3 bones in total.",
    "Rainbow eucalyptus trees have multicolored bark.",
    "The angel orchid looks like an angel with wings.",
    "A group of voles is called a nest.",
    "The human leg has 4 bones in total.",
    "Sensitive plants can learn and remember.",
    "The parrot flower looks like a flying parrot.",
    "A group of lemmings is called a slice.",
    "The average human body has 270 bones at birth.",
    "Acacia trees can warn other trees of danger.",
    "The skull orchid looks like a human skull.",
    "A group of martens is called a richness.",
    "Adult humans have 206 bones after some fuse together.",
    "Alarm pheromones help plants communicate threats.",
    "The laughing bumble bee orchid looks like it's laughing.",
    "A group of stoats is called a pack.",
    "The smallest bone in the human body is 2-3 millimeters long.",
    "Some trees can live over 5,000 years.",
    "The spider orchid looks exactly like a spider.",
    "A group of ermines is called a pack.",
    "The largest bone in the human body is 18 inches long.",
    "Trees can share nutrients through underground networks.",
    "The tiger orchid has stripes like a tiger.",
    "A group of fishers is called a pack.",
    "Human bones are 4 times stronger than concrete.",
    "Mother trees care for their offspring through root networks.",
    "The elephant orchid looks like an elephant's head.",
    "A group of polecats is called a chine.",
    "Human bones are constantly being broken down and rebuilt.",
    "Forest networks can span thousands of acres underground.",
    "The butterfly orchid looks like a butterfly in flight.",
    "A group of wolverines is called a pack.",
    "Human bones reach peak density around age 30.",
    "Trees can live in symbiosis with fungi for nutrients.",
    "The bird orchid looks like a bird with outstretched wings.",
    "A group of minks is called a nest.",
    "Bone density decreases by 1% per year after age 40.",
    "Some plants can recognize their own relatives.",
    "The cat orchid looks like a cat's face.",
    "A group of sables is called a pack.",
    "Human bones heal themselves when broken.",
    "Plants can alter their growth based on neighbors.",
    "The dragon orchid looks like a tiny dragon.",
    "A group of pine martens is called a richness.",
    "Bones are made of collagen and calcium phosphate.",
    "Some flowers track the sun throughout the day.",
    "The ghost orchid appears to float in mid-air.",
    "A group of otters in water is called a raft.",
    "Red blood cells are made in the bone marrow.",
    "Sunflowers can clean contaminated soil.",
    "The holy ghost orchid looks like a dove inside.",
    "A group of seals on land is called a colony.",
    "Bone marrow produces 200 billion red blood cells daily.",
    "Corn was originally the size of a small berry.",
    "The swaddled babies orchid looks like wrapped infants.",
    "A group of walruses is called a herd.",
    "Bones store 99% of the body's calcium.",
    "Bananas are clones and genetically identical.",
    "The white egret orchid looks like a flying egret.",
    "A group of manatees is called an aggregation.",
    "Bones also store phosphorus and magnesium.",
    "Carrots were originally purple, not orange.",
    "The flying duck orchid looks like a duck in flight.",
    "A group of dugongs is called a herd.",
    "Bone tissue is 22% water by weight.",
    "The happy alien orchid looks like a smiling alien.",
    "A group of narwhals is called a blessing.",
    "The periosteum covers bones and helps them heal.",
    "Rhubarb is technically a vegetable, not a fruit.",
    "The angry bird orchid looks like the game character.",
    "A group of beluga whales is called a pod.",
    "Compact bone is denser than spongy bone.",
    "Cashews grow on the bottom of cashew apples.",
    "The lizard orchid looks like a tiny lizard.",
    "A group of sperm whales is called a pod.",
    "Osteoblasts build new bone tissue.",
    "Peanuts grow underground and are legumes, not nuts.",
    "The moth orchid looks like a moth with spread wings.",
    "A group of orcas is called a pod.",
    "Osteoclasts break down old bone tissue.",
    "Vanilla comes from orchid pods, not beans.",
    "The donkey orchid looks like a donkey's head.",
    "A group of blue whales is called a pod.",
    "Osteocytes maintain bone tissue.",
    "Broccoli and cauliflower are the same species.",
    "The naked man orchid looks like tiny nude figures.",
    "A group of gray whales is called a pod.",
    "Bone remodeling takes about 10 years to complete.",
    "Brussels sprouts, kale, and cabbage are all the same plant.",
    "The angel orchid has pure white petals like wings.",
    "A group of humpback whales is called a pod.",
    "Weight-bearing exercise strengthens bones.",
    "Tomatoes were once thought to be poisonous.",
    "The lady slipper orchid looks like a tiny shoe.",
    "A group of minke whales is called a pod.",
    "Calcium and vitamin D are essential for bone health.",
    "Potatoes were the first vegetable grown in space.",
    "The bee orchid attracts pollinators that think it's a mate.",
    "A group of right whales is called a pod.",
    "Bone density can be measured with DEXA scans.",
    "The bucket orchid traps bees inside temporarily.",
    "A group of bowhead whales is called a pod.",
    "Osteoporosis makes bones brittle and weak.",
    "Chocolate was once used as currency.",
    "The hammer orchid looks like a tiny hammer.",
    "A group of fin whales is called a pod.",
    "Peak bone mass is usually reached by age 30.",
    "Coffee was discovered by goats eating coffee berries.",
    "The tongue orchid has a long protruding labellum.",
    "A group of sei whales is called a pod.",
    "Women lose bone density faster than men after menopause.",
    "Tea is the second most consumed beverage after water.",
    "The beard orchid has hair-like projections.",
    "A group of pilot whales is called a pod.",
    "Fractures heal through callus formation.",
    "Salt was once more valuable than gold.",
    "The swan orchid looks like a swimming swan.",
    "A group of dolphins and whales together is called a superpod.",
    "Bone grafts can help repair large fractures.",
    "Pepper was used to pay rent in medieval times.",
    "The tulip orchid looks like a tiny tulip flower.",
    "A group of porpoises is called a school.",
    "Artificial bones can be made from titanium.",
    "Saffron is worth more than its weight in gold.",
    "The star orchid has pointed star-shaped petals.",
    "A group of beaked whales is called a pod.",
    "Bone cancer can start in bones or spread from elsewhere.",
    "Quinoa was considered sacred by the Incas.",
    "The crown orchid has a regal crown-like appearance.",
    "A group of river dolphins is called a pod.",
    "Bone marrow transplants can treat blood cancers.",
    "Rice feeds more than half the world's population.",
    "The jewel orchid is grown for its beautiful leaves.",
    "A group of oceanic dolphins is called a school.",
    "Broken bones can become stronger after healing.",
    "Wheat is the most widely grown crop in the world.",
    "The night-blooming orchid only opens at night.",
    "A group of white-sided dolphins is called a pod.",
    "Stress fractures are small cracks from repetitive force.",
    "Corn is grown on every continent except Antarctica.",
    "The vanilla orchid is the only orchid used for food.",
    "A group of spinner dolphins is called a pod.",
    "Green stick fractures are incomplete breaks in children.",
    "Soybeans contain all nine essential amino acids.",
    "The chocolate orchid smells like chocolate.",
    "A group of spotted dolphins is called a pod.",
    "Compound fractures break through the skin.",
    "Avocados have more potassium than bananas.",
    "The coconut orchid smells like coconut.",
    "A group of striped dolphins is called a pod.",
    "Simple fractures don't break through the skin.",
    "Blueberries are one of the only naturally blue foods.",
    "The lemon orchid has a citrus scent.",
    "A group of Risso's dolphins is called a pod.",
    "Bone healing is faster in children than adults.",
    "Cranberries bounce when they're ripe.",
    "The rose orchid smells like roses.",
    "A group of rough-toothed dolphins is called a pod.",
    "Smoking slows bone healing significantly.",
    "Watermelons are 92% water.",
    "The cinnamon orchid smells like cinnamon spice.",
    "A group of Fraser's dolphins is called a pod.",
    "Alcohol interferes with bone formation.",
    "Oranges aren't naturally orange in tropical climates.",
    "The mint orchid has a refreshing mint scent.",
    "A group of Clymene dolphins is called a pod.",
    "Physical therapy helps bones heal properly.",
    "Apples float because they're 25% air.",
    "The honey orchid smells sweet like honey.",
    "A group of Atlantic white-sided dolphins is called a pod.",
    "Bone bruises are small fractures in the bone surface.",
    "Pineapples take two years to grow to full size.",
    "The almond orchid has a nutty almond scent.",
    "A group of Pacific white-sided dolphins is called a pod.",
    "Growth plates in bones close around age 18-25.",
    "Grapes explode when heated in a microwave.",
    "The jasmine orchid has an intense floral fragrance.",
    "A single raindrop can contain up to 1 million bacteria.",
    "The longest recorded surname has 666 letters.",
    "Your stomach acid is strong enough to dissolve razor blades.",
    "Antarctica has its own internet domain: .aq.",
    "A group of larks is called an exaltation.",
    "The human body glows in the dark, but it's too dim to see.",
    "Bubble wrap was originally invented as wallpaper.",
    "A group of crows can hold grudges for generations.",
    "The shortest complete sentence in English is 'I am.'",
    "A blue whale's tongue weighs as much as an elephant.",
    "The word 'mortgage' comes from French meaning 'death pledge.'",
    "A group of pugs is actually called a grumble.",
    "Your foot is the same length as the distance from your wrist to your elbow.",
    "A day on Pluto lasts 6.4 Earth days.",
    "The loudest animal on Earth is the sperm whale.",
    "A group of hippos in water is called a thunder.",
    "The human eye can see 10 million colors.",
    "Antarctica is technically the world's largest desert.",
    "A group of tigers is called a streak.",
    "The shortest bone in your body is in your ear.",
    "A sneeze can travel up to 160 kilometers per hour.",
    "The word 'literally' has been used figuratively for over 200 years.",
    "A group of jellyfish is also called a bloom.",
    "Your nose prints are as unique as your fingerprints.",
    "The Great Pyramid was the tallest building for 3,800 years.",
    "A group of owls is sometimes called a wisdom.",
    "The human brain uses the same amount of power as a 10-watt light bulb.",
    "The deepest place on Earth is the Mariana Trench at 36,200 feet.",
    "A group of squirrels is also called a dray.",
    "The longest hiccup attack lasted 68 years.",
    "Your saliva contains a natural painkiller stronger than morphine.",
    "A group of ravens can live up to 20 years in the wild.",
    "The word 'listen' and 'silent' use the same letters.",
    "A bolt of lightning is 5 times hotter than the Sun's surface and could power a house for 9 days.",
    "The smallest country in the world has its own train system.",
    "A group of peacocks is also called an ostentation.",
    "Your heart beats over 3 billion times in your lifetime.",
    "The longest word in any language has 189,819 letters.",
    "A group of flamingos flying is called a flamboyance.",
    "The human brain is 78% water.",
    "The deepest recorded dive by a mammal was 9,816 feet.",
    "A group of leopards is sometimes called a prowl.",
    "Your tongue is the strongest muscle in your body relative to its size.",
    "The fastest recorded tennis serve was 163.7 mph.",
    "A group of cats is sometimes called a clutter.",
    "Your human body is the host to trillions of small microscopic bugs!",
    /* "Qubits are bits that can be two things at once! Quantum physics is weird.", */
    "Astatine is the world's rarest element. Estimates show there's less than 1 gram in Earth's crust at any given time.",
    "Bananas make antimatter! This comes from Potassium-40 in the banana, which decays and emits one positron roughly every 75 minutes.",
    "No number before 1,000 contains the letter A.",
    "Your hand can quantum-tunnel through a wall, but 'the odds are about 1 in 10^(10^33) - so even smacking the wall 1,000 times a second for the Universe's entire 14-billion-year history wouldn't give you a single success,' meaning it's effectively impossible.",
    "Sharks are older than trees."
};

void tables_module_initialize(void)
{
    const char *p;
    char c;
    memset(character_map, 0, sizeof(character_map));

    /* Space */
    character_map[' '] |= CM_SPACE;
    character_map['\t'] |= CM_SPACE;
    character_map['\v'] |= CM_SPACE;

    /* Newline */
    character_map['\n'] |= CM_NEWLINE;
    character_map['\r'] |= CM_NEWLINE;

    /* Allowed in method */
    for (c = 'A'; c <= 'Z'; c++) character_map[(unsigned char)c] |= CM_METHOD;
    for (c = 'a'; c <= 'z'; c++) character_map[(unsigned char)c] |= CM_METHOD;
    for (c = '0'; c <= '9'; c++) character_map[(unsigned char)c] |= CM_METHOD;
    for (p = "!#$%&'*+-.^_'|~"; *p != '\0'; p++) character_map[(unsigned char)*p] |= CM_METHOD;

    /* Allowed in resource */
    for (c = '!'; c <= '~'; c++) character_map[(unsigned char)c] |= CM_RESOURCE; /*All visible ASCII*/

    /* Allowed in protocol */
    for (p = "HTTP/1.0"; *p != '\0'; p++) character_map[(unsigned char)*p] |= CM_PROTOCOL;

    /* Allowed in name */
    for (c = 'A'; c <= 'Z'; c++) character_map[(unsigned char)c] |= CM_NAME;
    for (c = 'a'; c <= 'z'; c++) character_map[(unsigned char)c] |= CM_NAME;
    for (c = '0'; c <= '9'; c++) character_map[(unsigned char)c] |= CM_NAME;
    for (p = "!#$%&'*+-.^_'|~"; *p != '\0'; p++) character_map[(unsigned char)*p] |= CM_NAME;

    /* Allowed in value */
    for (c = ' '; c <= '~'; c++) character_map[(unsigned char)c] |= CM_VALUE; /*All visible ASCII and space*/
}